name: CI

on:
  pull_request:
  push:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7

      - name: Set up JDK
        uses: actions/setup-java@v6
        with:
          cache: "gradle"
          java-version: "17"
          distribution: "temurin"

      - name: Unit tests
        run: ./gradlew testDebugUnitTest --no-daemon
